--- 
- name: Set Up Environment
  hosts: all
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
  - name: Checking NETCONF connectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: 830
      timeout: 5
  - name: Make a directory for each host
    file: 
      path: build/{{ inventory_hostname }}
      state: directory
      mode: 0755

- name: Run Show Commands
  hosts: all
  connection: local
  roles:
  - ethernet
  - interfaces
  - alarm
  - vlans
  - multicast
  - version
  - lacp








