--- 
- name: Run Show Commands
  hosts: all
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
  - name: Checking NETCONF connectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: 830
      timeout: 5
  - name: Make a directory for the host
    file: 
      path: build/{{ inventory_hostname }}
      state: directory
      mode: 0755
- name: Execute Roles
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  roles:
  - {role: version, tags: ['version']}
  - {role: vlan, tags: ['vlan']}
  - {role: commit, tags: ['commit']}
  - {role: interface, tags: ['interface']}
  - {role: alarm, tags: ['alarm']}
  - {role: ethernet, tags: ['ethernet']}
  - {role: multicast, tags: ['multicast']}
  - {role: lacp, tags: ['lacp']}
  - {role: rollback, tags: ['rollback']}
  - {role: config, tags: ['config']}
