--- 
- name: Run Show Commands
  hosts: all
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
  - name: Checking NETCONF connectivity
    wait_for:
      host: "{{ ansible_host }}"
      port: 830
      timeout: 5
  - name: Make a directory for the host
    file: 
      path: build/{{ inventory_hostname }}
      state: directory
      mode: 0755

- name: Run Show Commands
  hosts: all
  connection: local
  roles:
  - interfaces
  - alarm
- name: Run Switch Show Commands
  hosts: switches
  connection: local
  roles: 
  - ethernet
  - multicast
  - version
- name: Run Router Show Commands
  hosts: all
  connection: local
  ignore_errors: yes
  roles:
  - lacp




