---
- name: Show LACP Interfaces
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-lacp-interface-information
    format: xml
  register: result

- name: Save to file
  copy:
    content: "{{ result['parsed_output']['lacp-interface-information-list']['lacp-interface-information']['lag-lacp-protocol'] }}"
    dest: build/{{ inventory_hostname }}/lacp_table.json

- name: Get information to table
  command: python roles/lacp/scripts/show.py "{{ play_hosts }}" "{{ path }}"
  run_once: true
  delegate_to: localhost
  register: result
