---
- name: Show LACP Interfaces RPC
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-lacp-interface-information
    format: xml
  register: result
  ignore_errors: yes

- name: Save to file
  copy:
    content: "{{ result['parsed_output']['lacp-interface-information-list']['lacp-interface-information'] }}"
    dest: build/{{ inventory_hostname }}/lacp-information.json

- name: Get information to Web Server
  run_once: true
  local_action: command python roles/show.py "{{ play_hosts }}" "{{ path }}" lacp
