---
- name: Show Version
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-software-information
    format: xml
  register: result
  
- name: Save to file
  copy:
    content: "{{ result['parsed_output']['multi-routing-engine-results']['multi-routing-engine-item']['software-information']['package-information'] }}"
    dest: build/{{ inventory_hostname }}/version_table.json

- name: Get information to table
  command: python roles/version/scripts/show.py "{{ play_hosts }}" "{{ path }}"
  run_once: true
  delegate_to: localhost