---
- name: Get Vlan Information RPC
  juniper_junos_rpc: 
    provider: "{{ credentials }}"
    rpcs: get-vlan-information
    format: xml
  register: result

- name: Save to file
  copy:
    content: "{{ result['parsed_output']['l2ng-l2ald-vlan-instance-information']['l2ng-l2ald-vlan-instance-group'] }}"
    dest: build/{{ inventory_hostname }}/vlan-information.json

- name: Get information to Web Server
  command: python roles/vlans/scripts/show.py "{{ play_hosts }}" "{{ path }}"
  run_once: true
  delegate_to: localhost