---
- name: Show IGMP Snooping Membership RPC
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-igmp-snooping-membership-information
    format: xml
  register: result
- name: Save to file
  copy: 
    content: "{{ result['parsed_output']['igmp-snooping-group-information-root']['igmp-snooping-group-information-per-instance']['igmp-snooping-group-information-per-vlan'] }}"
    dest: build/{{ inventory_hostname }}/multicast-information.json

- name: Get information to Web Server
  run_once: true
  local_action: command python roles/show.py "{{ play_hosts }}" "{{ path }}" multicast

  