---
- name: get ethernet table json
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-ethernet-switching-table-information
    format: xml
  register: result
  
- name: Save to file
  copy:
    content: "{{ result['parsed_output']['l2ng-l2ald-rtb-macdb']['l2ng-l2ald-mac-entry-vlan']['l2ng-mac-entry'] }}"
    dest: build/{{ inventory_hostname }}/ethernet_switching_table.json

- name: Get the vlan ids
  juniper_junos_rpc: 
    provider: "{{ credentials }}"
    rpcs: get-vlan-information
    format: xml
  register: result

- name: Save to file
  copy:
    content: "{{ result['parsed_output']['l2ng-l2ald-vlan-instance-information']['l2ng-l2ald-vlan-instance-group'] }}"
    dest: build/{{ inventory_hostname }}/vlan-information.json

- name: Get information to table
  command: python roles/ethernet/scripts/show.py "{{ play_hosts }}" "{{ path }}"
  run_once: true
  delegate_to: localhost

  
