---
- name: Show Ethernet Switching Table RPC
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-ethernet-switching-table-information
    format: xml
  register: result
  
- name: Save to file
  copy:
    content: "{{ result['parsed_output']['l2ng-l2ald-rtb-macdb']['l2ng-l2ald-mac-entry-vlan']['l2ng-mac-entry'] }}"
    dest: build/{{ inventory_hostname }}/ethernet-information.json

- name: Get information to Web Server
  run_once: true
  local_action: command python roles/show.py "{{ play_hosts }}" "{{ path }}" ethernet


  
