--- 
- name: Show System Alarm RPC
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-system-alarm-information
    format: xml
  register: result
  
- name: Save to file
  copy:
    content: "{{ result['parsed_output']['alarm-information'] }}"
    dest: build/{{ inventory_hostname }}/alarm-information.json

- name: Get information to Web Server
  run_once: true
  local_action: command python roles/show.py "{{ play_hosts }}" "{{ path }}" alarm

