--- 
- name: Show System Alarm RPC
  juniper_junos_rpc:
    provider: "{{ credentials }}"
    rpcs: get-system-alarm-information
    format: xml
  register: result
  
- name: Save to file
  copy:
    content: "{{ result['parsed_output']['alarm-information'] }}"
    dest: build/{{ inventory_hostname }}/alarm_table.json

- name: Get information to Web Server
  command: python roles/alarm/scripts/show.py "{{ play_hosts }}" "{{ path }}"
  run_once: true
  delegate_to: localhost