version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/code
            - ../:/code/ansible
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - .:/code
            - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ../:/code/ansible
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
  